---
# tasks file for rhfedora
- name: Copy over RH SSSD template
  template:
    src: "sssd.j2"
    dest: /etc/sssd/sssd.conf
    mode: 0600
  register: sssd
    
- name: Copy over RH Kerberos template
  template:
    src: "krb5.j2"
    dest: /etc/krb5.conf

- name: Restarting SSSD to read in config files
  systemd:
    name: sssd
    state: restarted
    enabled: yes
  when: sssd.changed

- name: Authselect configuration (gross command module)
  command: authselect select sssd with-mkhomedir --force
  when: sssd.changed

- name: Enable and start oddjobd
  systemd:
    name: oddjobd
    state: started
    enabled: yes

- name: Ensures /etc/opt/chrome/policies/managed dir exists for kerberos configuration
  file: 
    path: /etc/opt/chrome/policies/managed 
    state: directory

- name: Configure Chrome to enable Kerberos auth for Red Hat
  copy:
    src: chrome-redhat-corp.json
    dest: /etc/opt/chrome/policies/managed/redhat-corp.json
    mode: 0644
      
