---
# tasks file for rhfedora
- name: Set hostname
  hostname:
    name: "{{ rh_kerberosid }}"

- name: Configuring fast mirrors
  lineinfile:
    path: /etc/dnf/dnf.conf
    line: 'fastestmirror=true'
    state: present

- name: Removing packages I deemed dumb
  dnf:
    name: "{{ remove_packages }}"
    state: absent
  tags:
    - online

- name: Upgrading all Existing System Packages
  dnf:
    name: "*"
    state: latest
  tags:
    - online

- name: Setup up RPM Fusion Repository
  dnf:
    name: "{{ rpmfusion }}"
    state: present
  tags:
    - online

- name: Installing Baseline Packages
  dnf:
    name: "{{ baseline_packages }}"
    state: latest
  tags:
    - online

- name: Copy VPN RPMs over
  copy:
    src: "{{ item }}"
    dest: /tmp/vpn/
  with_fileglob: "*.rpm"  
  register: vpn_files

- name: Set VPN RPM variable    
  set_fact:
    vpn_rpms: "{{ vpn_files.results | map(attribute='dest') | list}}"

- name: Installing VPN Packages
  yum:
    name: "{{vpn_rpms}}"
  tags:
    - online  
    

