---
# tasks file for rhfedora
- name: Configuring fast mirrors
  lineinfile:
    path: /etc/dnf/dnf.conf
    line: 'fastestmirror=true'
    state: present

- name: Upgrading all Existing System Packages
  dnf:
    name: "*"
    state: latest

- name: Installing Baseline Packages
  dnf:
    name: "{{ baseline_packages }}"
    state: latest
