---
# tasks file for rhfedora
- name: Upgrading all Existing System Packages
  dnf:
    name: "*"
    state: latest

- name: Installing Baseline Packages
  dnf:
    name: "{{ baseline_packages }}"
    state: latest
 

