---
# tasks file for rhfedora
- name: Upgrading all Existing System Packages
  dnf:
    name: "*"
    state: latest

- name: Installing Baseline Packages
  dnf:
    name: "{{ baseline_packages }}"
    state: latest

- name: Make directory for third party apps /tmp/rpms
  file:
    path: /tmp/rpms
    state: directory
    
- name: Download Non-DNF installabe packages
  get_url:
    url: "{{ baseline_downloads }}"
    dest: /tmp/rpms
  register: rpms_copied

- name: Validate RPMS were downloaded
  fail:
    msg: "RPMs not found in ../files/"
  when: rpms_copied.results|length == 0 and rpms_copied.skipped and rpms_copied.skipped_reason.find('No items') != -1

- set_fact:
    rpm_list: "{{ rpms_copied.results | map(attribute='dest') | list}}"

- name: Install Non-DNF Downloaded packages
  yum:
    name: "{{rpm_list}}"
